#!/usr/bin/env node
/**
 * Deployment gate. Checks the running environment against config-spec.mjs
 * and refuses to say it's fine while any required value is missing or still
 * equal to the placeholder it shipped with — a value present but unchanged
 * is not configured, it's ignored.
 *
 * Usage:
 *   node deploy/preflight.mjs                    # check process.env, exit 78 on failure
 *   node deploy/preflight.mjs --write-template <path>   # (re)generate an env template
 *
 * api/src/server.js calls runPreflight() before binding a port in production.
 */

import { writeFileSync } from "node:fs";
import { SPEC, REQUIRED_GROUPS } from "./config-spec.mjs";

const ROLE_MAP_ENTRY = SPEC.find((e) => e.name === "AUTH_ROLE_MAP");

function isRequired(entry, env) {
  if (entry.requiredWhen) return entry.requiredWhen(env);
  return Boolean(entry.required);
}

function checkRoleMap(env, failures) {
  // Unset falls through to config.js's own default, which IS the
  // placeholder map -- so "unset" must be checked exactly like "still the
  // placeholder", not skipped.
  const raw = env.AUTH_ROLE_MAP || ROLE_MAP_ENTRY.default;
  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch {
    failures.push({ name: "AUTH_ROLE_MAP", reason: "not valid JSON" });
    return;
  }
  for (const [role, placeholderGroup] of Object.entries(REQUIRED_GROUPS)) {
    if (Object.keys(parsed).includes(placeholderGroup)) {
      failures.push({
        name: "AUTH_ROLE_MAP",
        reason: `still maps the placeholder group '${placeholderGroup}' (${role}) — replace with rain's real directory group`,
      });
    }
  }
}

/**
 * @param {Record<string,string|undefined>} env
 * @returns {{ ok: boolean, failures: Array<{name: string, reason: string}> }}
 */
export function runPreflight(env) {
  const failures = [];

  for (const entry of SPEC) {
    if (entry.name === "AUTH_ROLE_MAP") continue; // checked separately, below
    const value = env[entry.name];
    const required = isRequired(entry, env);

    if (required && (value === undefined || value.trim() === "")) {
      failures.push({ name: entry.name, reason: "missing" });
      continue;
    }
    if (value !== undefined && entry.placeholder !== undefined && value === entry.placeholder) {
      failures.push({ name: entry.name, reason: `still the shipped placeholder (${entry.placeholder})` });
    }
  }

  checkRoleMap(env, failures);

  return { ok: failures.length === 0, failures };
}

export function generateTemplate(spec = SPEC) {
  const lines = [
    "# Generated by deploy/preflight.mjs --write-template. Do not hand-edit the",
    "# values below this line -- edit deploy/config-spec.mjs and regenerate.",
    "",
  ];
  for (const entry of spec) {
    if (entry.note) lines.push(`# ${entry.note}`);
    const required = entry.required || entry.requiredWhen ? " (REQUIRED)" : "";
    if (required) lines.push(`# REQUIRED${entry.requiredWhen ? " when AUTH_MODE != dev" : ""}`);
    const value = entry.placeholder ?? entry.default ?? "";
    lines.push(`${entry.name}=${value}`);
    lines.push("");
  }
  return lines.join("\n").trimEnd() + "\n";
}

function main() {
  const args = process.argv.slice(2);
  const writeIdx = args.indexOf("--write-template");

  if (writeIdx !== -1) {
    const path = args[writeIdx + 1];
    if (!path) {
      console.error("--write-template requires a file path");
      process.exit(2);
    }
    writeFileSync(path, generateTemplate());
    console.log(`wrote ${path}`);
    return;
  }

  const result = runPreflight(process.env);
  if (!result.ok) {
    console.error("preflight failed:");
    for (const f of result.failures) {
      console.error(`  ${f.name}: ${f.reason}`);
    }
    process.exit(78);
  }
  console.log("preflight passed");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
